### ISSUE TITLE
Allow hooking functions from outside the script

### ISSUE THREAD

**Issue by BurhanDanger** [aerobounce/trim.lua#1]
I use `no-input-default-bindings` and configure keys through input.conf . Please add instructions for that. Thanks.

**Comment by BurhanDanger** [comment]
Also a separate minor issue. You hadcoded location to /usr/local/bin but for my arch install these binaries are in /usr/bin . I changed location so not really any major issue.

**Comment by aerobounce** [comment]
I've never used `no-input-default-bindings` option, did a bit google and found: https://github.com/mpv-player/mpv/issues/2584
Does this help you?
If not, could you provide some example scripts that already satisfy your case (or way how you resolve with other scripts), so that I might be able to learn and adopt architectures.

I'm assuming you can bind `script-message` command to a key though, `trim.lua` has some anonymous functions so needs a bit of refactoring.

**Comment by aerobounce** [comment]
Haven't used this script for a while actually though, reviewed entire codes and it utilizes key-bind dynamically but not statically.

Anyways, I'm not adding "instructions", as that's something a user should learn. But you led me to a good point, I might refactor codes to allow hooking by `input.conf` in the future.
I edited the title accordingly.

**Comment by BurhanDanger** [comment]
I could configure your script with `no-input-default-bindings`, partially. I couldn't use that Seeking and Adjust Current Keyframe with input.conf

**Comment by aerobounce** [comment]
Yes, that's because those functions are nameless, which you can't simply bind in `input.conf`.

And yeah, I re-thought about all of this and you're correct. It's simply just nice to have a way to let users to bind whatever or however they like.
The problem is some key-bindings are done on the very first press of <kbd> h </kbd> or <kbd> k </kbd>, and this is intended, because you don't want it all the time you use mpv.

**Comment by BurhanDanger** [comment]
> The problem is some key-bindings are done on the very first press of h or k, and this is intended, because you don't want it all the time you use mpv.

Are you saying that 'Seeking' and 'Adjust Current Keyframe' only gets activated after the first press of `h`/`k`. If so then my mpv is bugged. If I press shift+right , then consequent shift+h or shift+k gets me to the beginning of video. Also to note that shift+left/right are default mpv keybindings.

> Yes, that's because those functions are nameless, which you can't simply bind in input.conf

Okay. It's not an issue for me really. Even if I could use them with input.conf , I wouldn't . I already have too many key bindings to remember. I normally disable the bindings that I don't need/use. But it's nice to know that it can be configured with input.conf if someone wants to.

**Comment by BurhanDanger** [comment]
Take a look at this awesome mpv script https://github.com/occivink/mpv-scripts#croplua
This person gave configurable keybindings to user via `crop.conf`.

**Comment by aerobounce** [comment]
The latest version of the script has following bindings by default:

```
mp.add_key_binding("h", "save-start-position", saveStartPosition)
mp.add_key_binding("k", "save-end-position", saveEndPosition)
```

You can hook them in `input.conf` in this manner:
```
s script-message "save-start-position"
e script-message "save-end-position"
```

Hope this helps 👍
